### ISSUE TITLE
deepsignal2 vs deepsignal ?

### ISSUE THREAD

**Issue by pterzian** [PengNi/deepsignal2#1]
Hi Peng,

Glad to see a new version of deepsignal !
I have some questions: 
* Did you already do a comparison of both tools (deepsignal vs deepsignal2) ? Did you use the same dataset to build the model ? Is it faster ? etc)
* Can we use this new version to train models the same way we did before ? Are you still using the bisulfite-based strategy to find high confidence sites ?

Best,
Paul

**Comment by PengNi** [comment]
Hi Paul,

- We used the same dataset (HX1 nanopore reads) to train the models of deepsignal and deepsignal2. deepsignal2 has sligtly higher performance than deepsignal: 0.8879 vs 0.8824 pearson correlation with BS-seq using 5x nanopore reads. We did not test runnning time, but deepsignal2 should be a little faster.
- Yes, we used the bisulfite-based strategy to find high confidence sites, and the train processes of the two tools are basicly the same. Please check [generate_samples_and_train.sh](https://github.com/PengNi/deepsignal2/blob/master/scripts/generate_samples_and_train.sh) for more details.

Best,
Peng

**Comment by pterzian** [comment]
Thank you for these answers.
I am trying to understand if I can use features files extracted with the first version of deepsignal to train a model with deepsignal2. Or, call previously extracted features with your new model.
I see you made some modifications to the features format and I would like to be sure of what I understood.
From these lines of code :
 
https://github.com/PengNi/deepsignal2/blob/2136cb258f156046ac7163f6dfd257ca09891d28/deepsignal2/extract_features.py#L316

https://github.com/PengNi/deepsignal2/blob/2136cb258f156046ac7163f6dfd257ca09891d28/deepsignal2/call_modifications.py#L69

I understand you split the raw signal of one base with `,` and sets of raw signal  with `;` ?

If 1 base = 3 signal values it would be written out like this :

```
0.0,0.0,0.0;0.0,0.0,0.0;etc
```

Is this the only change between both features format file ?

**Comment by PengNi** [comment]
Yes, it's the only change. In deepsignal, we extract at most 360 signal values centered in the raw signals of 17mer; in deepsignal2, we extract at most 16 signals of each base, to form 17*16 matrix.

Best,
Peng
