### ISSUE TITLE
Error after Basecalling

### ISSUE THREAD

**Issue by JayVaz18** [PengNi/deepsignal2#2]
Hello, 

I am trying to generate base modifications for my reads from guppy. I have been following the README as you have provided and seem to be getting an error after generating the .fastq file using guppy Basecall. 

This is the command I used:

```
tombo preprocess annotate_raw_with_fastqs --fast5-basedir /Users/jakevazquez18/Desktop/guppy/fast5/ --fastq-filenames fastq_runid_2ec6d299c207e5b8d21d7ecd496b26c424033791_0_0.fastq --basecall-group Basecall_1D_000 --basecall-subgroup BaseCalled_template --overwrite --processes 10

```
And here is the error:

```

[13:46:08] Preparing reads and extracting read identifiers.
/Users/jakevazquez18/anaconda3/envs/py36/lib/python3.6/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/Users/jakevazquez18/anaconda3/envs/py36/lib/python3.6/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
****** WARNING ****** Basecalls exsit in specified slot for some reads. Set --overwrite option to overwrite these basecalls.
100%|█████████████████████████████████████████████| 2/2 [00:00<00:00, 18.61it/s]
[13:46:08] Annotating FAST5s with sequence from FASTQs.
****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencing summary files.
0it [00:00, ?it/s]
[13:46:08] Added sequences to a total of 0 reads.

```

**Comment by PengNi** [comment]
@JayVaz18 , your log show that there are `2/2` items processed. So I guess that your fast5 reads are in multi-reads format. If so, the fast5 files must be converted to single-read format by [ont_fast5_api](https://github.com/nanoporetech/ont_fast5_api). See [README ](https://github.com/PengNi/deepsignal2#1-basecall-and-re-squiggle)for more details.

Hope that could help!

Best,
Peng

**Comment by JayVaz18** [comment]
> @JayVaz18 , your log show that there are `2/2` items processed. So I guess that your fast5 reads are in multi-reads format. If so, the fast5 files must be converted to single-read format by [ont_fast5_api](https://github.com/nanoporetech/ont_fast5_api). See [README ](https://github.com/PengNi/deepsignal2#1-basecall-and-re-squiggle)for more details.
> 
> Hope that could help!
> 
> Best,
> Peng

Awesome, it works. Thanks! Great tool and usage of Deep Learning.
