### ISSUE TITLE
Can the context of searching for methylation be altered slightly?

### ISSUE THREAD

**Issue by JayVaz18** [PengNi/deepsignal2#3]
Hello,

I'm loving using your tool so far. I did have a quick question regarding the search for methylation. I was wondering if it was possible to search for methylation on ONLY base C and NOT base G? I know currently it searches for CpG islands, but I was wondering if it would be possible to remove G from the context. 

Thanks.

**Comment by PengNi** [comment]
Hi @JayVaz18 , deepsignal2 does not have a model for 5mC detection in non-CpG context. If you are interested, you can try our another tool [deepsignal-plant](https://github.com/PengNi/deepsignal-plant), which is designed for 5mC detection in all contexts (CpG, CHG, CHH) of plants. However, we only test deepsignal-plant in plant genomes. The performance in Yeast genome if not yet tested.

Best,
Peng

**Comment by JayVaz18** [comment]
Ah okay. Do you know if there's a way I can make modifications to the model in the source code to only look for C methylation or is that not possible because of how the model is constructed?

**Comment by PengNi** [comment]
Maybe there's misunderstanding here. When using the pre-trained model, we actually call only C methylation in CG (_i.e._, CpG) contexts. I am not sure if you are worrying about that the model will call G methylation at the same time (which the model doesn't do such a thing and G methylation doesn't exist in real life), or you want to call C methylation in other contexts (such as CHG and CHH).

Again, the pre-trained model of deepsignal2 can only detect 5mC in CpG contexts, and is not suited for 5mC in non-CpG contexts.

Hope that could help!

Best,
Peng
