### ISSUE TITLE
tagged release

### ISSUE THREAD

**Issue by wresch** [PengNi/deepsignal2#4]
Hi there,

We have deepsignal installed on our cluster and just received a request for deepsignal2.  But i see that you don't have any tags yet. Do you consider this to be ready for use? If so, would you mind creating a tag? We prefer not to install just the head of a repo which makes it harder for users to understand exactly which version of  a tool they are using.

Thanks,
Wolfgang

**Comment by PengNi** [comment]
Hi @wresch , thanks for your insteresting of our tool. deepsignal2 is ready for use, and we just released a tag `0.1.0` of deepsignal2.

Best,
Peng

**Comment by wresch** [comment]
Great. Thank you.

Wolfgang
