### ISSUE TITLE
question about 'deepsignal2 call_mods ' commands

### ISSUE THREAD

**Issue by Flower9618** [PengNi/deepsignal2#8]
Hi, 

   I am confused about the argument '--methy_label' in the 'deepsignal2 call_mods' command.  If I have one dataset that includes both the methylated and unmethylated class, how should I set the argument '--methy_label'?
  Thank you very much!

Best,
Rong

**Comment by PengNi** [comment]
Hi @Flower9618 , sorry for the confusion. `--methy_label` is only designed for training. When use=ing `call_mods` module, this argument is not used. So it doesn't matter what number you set.

Best,
Peng

**Comment by Flower9618** [comment]
> Hi @Flower9618 , sorry for the confusion. `--methy_label` is only designed for training. When using `call_mods` module, this argument is not used. So it doesn't matter what number you set.
> 
> Best, Peng

Thank you very much for your prompt reply. So, When I use 'deepsignal2 call_mods' command, it will just use the trained model to call methylation, '--methy_Label' is not used. But in the 'deepsignal2 extract' command， the argument '--methy_label' is used. Is I correct?

**Comment by PengNi** [comment]
@Flower9618, yes, this is correct.
