### ISSUE TITLE
All fast5 files failed

### ISSUE THREAD

**Issue by neobernad** [PengNi/deepsignal2#9]
Hi,

We have launched `deepsignal2` and it seems it cannot process our fast5 files, the log states:

```bash
...
...
call_mods process-29575 ending, proceed 0 batches
write_process-29577 starts
write_process-29577 finished
764774 of 764774 fast5 files failed..
[main]call_mods costs 2978.95 seconds..
```

Thus 764774 out of 764774 failed. Are we doing something wrong? We are using `tombo` and `deepsignal2` as follows:

- Commands for `tombo`:
```bash
tombo preprocess annotate_raw_with_fastqs --fast5-basedir {input.fast5_folder} --fastq-filenames {input.fastq_file} --sequencing-summary-filenames {input.sequencing_summary} --basecall-group "Basecall_1D_000" --basecall-subgroup "BaseCalled_template" --overwrite

tombo resquiggle {input.fast5_folder} {input.reference} --corrected-group "RawGenomeCorrected_000" --basecall-group "Basecall_1D_000" --overwrite
```
- Command for `deepsignal2` (CPU-based execution):
```bash
CUDA_VISIBLE_DEVICES=-1 deepsignal2 call_mods --input_path {input.fast5_folder} --model_path "model.dp2.CG.R9.4_1D.human_hx1.bn17_sn16.both_bilstm.b17_s16_epoch4.ckpt" --result_file {output.methylation_info_tsv} --corrected_group "RawGenomeCorrected_000" --reference_path {input.reference} --motifs "CG"
```

**Note**: Neither reference genome nor fast5 files are coming from human, just in case it is an issue.

Best,
José Antonio

**Comment by PengNi** [comment]
Hi José, 

Thanks for using our tool. 

What did the log of tombo preprocess/resquiggle say? Did these two steps succeed? If the tombo steps succeed, then I'll check more for deepsignal2.

Best,
Peng

**Comment by neobernad** [comment]
Hello @PengNi,

Thanks for your fast reply!

I do not have the log of preprocess but resquiggle. The last part of it shows:

```bash
[15:58:40] Final unsuccessful reads summary (53.6% reads unsuccessfully processed; 410059 total reads):
    31.9% ( 243717 reads) : Reference mapping contains non-canonical bases (transcriptome reference cannot contain U bases)
    10.2% (  77835 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`) 
     9.8% (  74924 reads) : Alignment not produced                                                          
     1.8% (  13520 reads) : Read event to sequence alignment extends beyond bandwidth                       
     0.0% (     35 reads) : Read failed sequence-based signal re-scaling parameter estimation.              
     0.0% (     19 reads) : Not enough raw signal around potential genomic deletion(s)                      
     0.0% (      7 reads) : Fewer changepoints found than requested                                         
     0.0% (      1 reads) : Unexpected error                                                                
     0.0% (      1 reads) : Too much raw signal for mapped sequence                                         
[15:58:40] Saving Tombo reads index to file.
``` 

It seems that 53.6% of the reads could not be processed properly, but at least it could process the rest, 410059 out of 764774. Thus I would expect to process at least 410059 reads in `deepsignal2` (?).

**Comment by PengNi** [comment]
@neobernad , yes, deepsignal2 should be able to process the rest successful reads. Acoording to the log of tombo, it seems that deepsignal2 is the problem. May you send me some  (like 10 or 100) fast5s and the reference genome you used, so I can test the code of deepsignal2 myself?

**Comment by neobernad** [comment]
Hi @PengNi,
Thanks for taking a look into this, it is much appreciated.
Please find attached 100 fast5.
[sample_fast5.zip](https://github.com/PengNi/deepsignal2/files/7777714/sample_fast5.zip)
.

**Comment by PengNi** [comment]
Hi @neobernad ,

It is caused by the vbz compression issue. I export the HDF5_PLUGIN_PATH as follows and it worked:
```shell
# 2. download ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz (or newer version) and set HDF5_PLUGIN_PATH
# https://github.com/nanoporetech/vbz_compression/releases
wget https://github.com/nanoporetech/vbz_compression/releases/download/v1.0.1/ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz
tar zxvf ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz
export HDF5_PLUGIN_PATH=/abslolute/path/to/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin
```

please have a try.

Best,
Peng

**Comment by neobernad** [comment]
Hello @PengNi,

Thank you so much, that did the trick! Much appreciated :-).

Best,
José Antonio
